In [4]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

sample = np.array([5,4,3,2,1,0]).reshape(3,2)
print("일차 단항식 feature : \n{}".format(sample))

일차 단항식 feature : 
[[5 4]
 [3 2]
 [1 0]]


In [5]:
poly = PolynomialFeatures(degree=3)
poly.fit(sample)

poly_ftr = poly.transform(sample)
print("이차 다항식 feature : \n{}".format(poly_ftr))


이차 다항식 feature : 
[[  1.   5.   4.  25.  20.  16. 125. 100.  80.  64.]
 [  1.   3.   2.   9.   6.   4.  27.  18.  12.   8.]
 [  1.   1.   0.   1.   0.   0.   1.   0.   0.   0.]]
