In [ ]:
# numpy 모듈 불러오기
import numpy as np

-넘파이는 C언어로 구현되어 있어서 속도가 빠름! + 파이썬의 사용성
(단점 : GPU지원이 안됨)

-수치 연산에 관련된 방대한 라이브러리가 존재(with scipy)

-일반 파이썬 수치연산보다 훨씬 빠름

-특히 배열 병렬 연산에 특화되어 있다.(뭔가 동시에 연산한다는 느낌? 행렬 더하기할때 )

# numpy의 배열을 ndarray라고 한다

In [ ]:
# ndarray 만들기
# python의 list를 ndarray화 하기!
py_list = [1,2,3]
arr1 = np.array(py_list)
arr1

array([1, 2, 3])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1[0], arr1[2], arr1[-1]
# array도 순서가 있기 때문에 인덱스 사용 가능!

(1, 3, 3)

# 배열의 종류
1. 스칼라
  - 0차원 데이터(데이터의 진행방향의 개수)
  - 측정한 하나의 값.
  ex) 키 = 180.1 나이 = 34 몸무게 = 80.5

2. 벡터
  - 1차원 배열
  - 스칼라가 연속적으로 모여있는 것
  - 3명의 키를 하나로 모은다
  ex) 사람키 = [180.1 173.5, 177.8] 3-dimensional vector(feature)

3. 행렬
  - 2차원 배열 ()
  - 1차원 배열인 벡터가 여러개 모여있는 것.

4. 텐서
  - 3차원 이상의 배열 (()행렬이 뒤로 쭈우욱있는모양)
  - 0 rank tensor = 스칼라
  - 1 rank tensor = 벡터
  - 2 rank tensor = 행렬
  
  텐서로 모든 배열의 모양을 이야기 할 수 있다.

# tensorflow란?
  - 구글에서 제공하는 딥러닝 프레임워크
  - 미리 준비된 네트워크에 tensor를 흘린다.


# numpy 함수 알아보기!

np.arange
-파이썬의 range와 흡사

In [ ]:
arr = np.arange(10)  #0~9까지 정수
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## np.zeros, np.ones, np.full
  - 다차원 배열을 만들 수 있다.

In [ ]:
np.zeros(5)  #0차원 5개로 1차원 배열 만듦!


array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))  # shape을 넣어서 2X3으로 만들어 줄 수 있음!
# 2차원 배열을 생성. 1차원 배열이 2개, 1차원 배열에 추가되는 0차원 스칼라가 3개

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,4,5)) # 3차원 배열(텐서)을 만들었음. 2차원배열 3개 / 1차원4 개 /0차원 5개!

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# full : 원하는 값으로 배열을 채우는거!
np.ones((2,3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [ ]:
np.full((2,3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

# Random 사용하기

## np.random.rand
- 완전 랜덤 만들기! 진짜걍 랜덤

In [ ]:
np.random.rand(2,3)

array([[0.55592205, 0.49260001, 0.24625429],
       [0.37546581, 0.86961324, 0.42865569]])

In [ ]:
np.random.rand(2,3,4)

array([[[0.41119875, 0.68378729, 0.45319908, 0.32584233],
        [0.41817386, 0.4944925 , 0.61116392, 0.15063562],
        [0.54409493, 0.63638547, 0.42170139, 0.71782815]],

       [[0.57566162, 0.58494682, 0.48979057, 0.09567817],
        [0.99775883, 0.11796854, 0.51576228, 0.22864585],
        [0.55426839, 0.73567382, 0.53360314, 0.75239733]]])

## np.random.randn
- 정규분포로 이루어진 랜덤값 만들기!

In [ ]:
np.random.randn(2,3)

array([[-0.06514351, -1.1985984 , -1.50209073],
       [-1.20696691,  0.52104298, -0.4955352 ]])

In [ ]:
np.random.randn(16)

array([-0.15060592, -0.71375386,  1.11030236, -1.18340619, -1.62889018,
        1.27248745,  1.89138785, -0.46209602, -0.04597001, -1.14666471,
        0.00549255, -0.47570526, -0.10212844,  0.40925839, -1.09814548,
       -0.36181134])

## np.random.uniform
  - 균등분포 랜덤값 만든다.
  - 최소 한계점, 최대 한계점을 같이 입력한다.

  연속확률변수 X가 한 구간의 임의의 점을 '동일한 확률'로 취할 때 X는 그 구간에서 '균등분포'를 따른다고 한다.

In [ ]:
np.random.uniform(1.0, 3.0, size=(4,5))

array([[1.50926767, 2.85252129, 1.2868732 , 2.02130471, 1.78153979],
       [2.50819574, 2.19682872, 2.15468794, 1.08475624, 1.50244899],
       [1.74135655, 2.54781007, 2.43146944, 2.37973319, 2.60693634],
       [1.08616168, 1.19270719, 1.27860733, 2.63314772, 2.49109047]])

## 벡터를 행렬로 표현해 보기
- 1차원 배열을 2차원배열로 표현해보기!

In [ ]:
x = np.random.rand(5)
x
# 생긴건 행벡터마냥 보이는데  😊❤ R^5열벡터 ❤😊임 사용하거나 인지할땐 열벡터로 인식해야됨.

array([0.01822951, 0.729989  , 0.66222588, 0.51408373, 0.30539121])

In [ ]:
x.T
# transpose 전치가 안됨  R^5X1 이아니라 그냥 R^5에 들어가있는거라서 행렬개념이아니기 때문
# 1차원 배열은 = 벡터다! 행렬이아니라 트랜스포즈가 안된당⭐
# 즉, 행벡터를 만들 수 없다

array([0.01822951, 0.729989  , 0.66222588, 0.51408373, 0.30539121])

In [ ]:
y = np.random.rand(2,3)
y

array([[0.11212184, 0.17366952, 0.92693621],
       [0.06091159, 0.98072364, 0.57405711]])

In [ ]:
y.T
# 행렬은 문제없이 되넹

array([[0.11212184, 0.06091159],
       [0.17366952, 0.98072364],
       [0.92693621, 0.57405711]])

In [ ]:
# 올바른 열벡터 만드는 방법
x = np.random.rand(5,1)  #이건 매트릭스라서 전치됨! 😊X1 써줘야함!
x

array([[0.29644167],
       [0.43089735],
       [0.0859774 ],
       [0.7601284 ],
       [0.06915414]])

In [ ]:
x.T # = np.random.rand(1,5) 행벡터도 만들수있징

array([[0.29644167, 0.43089735, 0.0859774 , 0.7601284 , 0.06915414]])

# axis(축)
데이터의 진행 방향이라고 보면됨

축의 index⭐⭐⭐

1차원배열 = 벡터의 축은 한방향. axis = 0번

2차원배열 = 행렬의 축은 행,렬 두방향 axis= 0,1번

  행,렬 순서 ↓0번 →1번


In [ ]:
arr = np.arange(5)
arr  # 1차원배열 = 벡터
# → aixs 0번 하나밖에 없음

array([0, 1, 2, 3, 4])

In [ ]:
np.max(arr, axis=0)
# 축에서 제일 큰값 찾아줌!

4

In [ ]:
np.random.seed(42)  # 랜덤 고정 강사님이랑 값 똑같이하려고
arr = np.random.randint(1, 6, size=(2,3))  #randint 1~5까지 랜덤한 정수배열 만들기
arr

array([[4, 5, 3],
       [5, 5, 2]])

In [ ]:
# ⭐⭐⭐⭐⭐⭐⭐
# 축이 2개 ↓ axis 0
#          → axis 1

In [ ]:
np.max(arr, axis=0) # ↓ axis 0 이방향으로 3번 반복 (1열끼리비교 2열끼리비교 3열끼리비교)

array([5, 5, 3])

In [ ]:
np.max(arr, axis=1) # → axis 1 이방향으로 2번 반복 (1행끼리비교 2행끼리비교)

array([5, 5])

In [ ]:
np.random.seed(42)

arr = np.random.randint(1, 100, size=(3,4))
arr

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]])

In [ ]:
np.max(arr, axis=1)

array([93, 87, 88])

In [ ]:
np.min(arr, axis=0)

array([52, 21, 15, 24])

## 3차원 배열 예제

In [ ]:
arr = np.random.randint(1,100, size=(3,4,3))  1~99까지 정수
arr

array([[[ 3, 22, 53],
        [ 2, 88, 30],
        [38,  2, 64],
        [60, 21, 33]],

       [[76, 58, 22],
        [89, 49, 91],
        [59, 42, 92],
        [60, 80, 15]],

       [[62, 62, 47],
        [62, 51, 55],
        [64,  3, 51],
        [ 7, 21, 73]]])

In [ ]:
#randint는 end-1까진가벼

arr = np.random.randint(1,2, size=(10,10))
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
np.max(arr, axis=0) # 행렬 3개 끼리 비교 ↗방향으로 매트릭스가 겹쳐져 뒤로 쭈우욱⭐
# 3, 76, 62끼리 비교 !! x11끼리 비교 x12끼리비교 x13끼리비교...
# 22, 58, 62끼리 비교!!
# 53, 22, 47끼리 비교!

array([[76, 62, 53],
       [89, 88, 91],
       [64, 42, 92],
       [60, 80, 73]])

In [ ]:
np.min(arr, axis=2) # →방향

array([[ 3,  2,  2, 21],
       [22, 49, 42, 15],
       [47, 51,  3,  7]])

In [ ]:
np.max(arr, axis=1) # ↓방향

array([[60, 88, 64],
       [89, 80, 92],
       [64, 62, 73]])

In [ ]:
# argmax 값이 젤 큰 위치의 ⭐ index 인덱스가나옴!⭐
np.argmax(arr, axis=0)

# 3, 76, 62 비교해서 76이 젤 크니까 매트릭스 0, 1, 2번중 1번

array([[1, 2, 0],
       [1, 0, 1],
       [2, 1, 1],
       [0, 1, 2]])

In [ ]:
np.argmax(arr, axis=1) # ↓방향 
# 0
# 1
# 2
# 3 index

array([[3, 1, 2],
       [1, 3, 2],
       [2, 0, 3]])

In [ ]:
# 스터디 때 내가 직접 예제 해보기!

ar = np.random.randint(1,100, size=(4,2,3))
ar

array([[[39, 18,  4],
        [89, 60, 14]],

       [[ 9, 90, 53],
        [ 2, 84, 92]],

       [[60, 71, 44],
        [ 8, 47, 35]],

       [[78, 81, 36],
        [50,  4,  2]]])

In [ ]:
np.max(ar, axis=0)

array([[78, 90, 53],
       [89, 84, 92]])

In [ ]:
np.min(ar, axis=1)

array([[39, 18,  4],
       [ 2, 84, 53],
       [ 8, 47, 35],
       [50,  4,  2]])

In [ ]:
np.argmax(ar, axis=2)

array([[0, 0],
       [1, 2],
       [1, 1],
       [1, 0]])

In [ ]:
np.argmin(ar, axis=1)

array([[0, 0, 0],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
py_list = [4,4,4]
arr1 = np.array(py_list)
arr1

array([4, 4, 4])

In [ ]:
np.argmax(arr1, axis=0)
# 같은값이면 젤 앞의 index가 나옴

0

# 배열의 인덱싱과 슬라이싱


In [ ]:
np.random.seed(42)

arr = np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr[1][0] #index는 0부터

3

In [ ]:
arr[1][1]

4

In [ ]:
arr[1,1]  #이렇게 해도됨

4

## fancy indexing
  - 가지고 오고 싶은 데이터의 인덱스를 리스트에 넣어서 조회하는 방법

In [ ]:
arr = np.arange(10,70,10)
arr

NameError: ignored

In [ ]:
# 20이랑 50을 ⭐동시에⭐ 가지고오고싶다
arr[[1,4]] # []안에 []넣으면됨💕
# arr[1], arr[4] 랑 다름이건 (20,50)형태로 나옴

array([20, 50])

In [ ]:
arr = np.arange(36).reshape(4,9)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [ ]:
# 01항 34항 17항이 나옴!
arr[[0,3,1],[1,4,7]]

array([ 1, 31, 16])

In [ ]:
arr[[0,3]]

# 0행, 3행이나옴

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [ ]:
arr[[1,0],[1,2]]

array([10,  2])

# 슬라이싱

In [ ]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[3:7]  # 리스트 슬라이싱이랑 똑같음

array([4, 5, 6, 7])

In [ ]:
arr = np.arange(1,37).reshape(4,9)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36]])

In [ ]:
arr[1:3,2:7]  # 행먼저 자르고, 열자름 end - 1까지

array([[12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25]])

In [ ]:
arr = np.arange(1,37).reshape(3,4,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [ ]:
# 문제! [16,17,18,19,20,21]뽑아내기
arr[1,1:3]

array([[16, 17, 18],
       [19, 20, 21]])

In [ ]:
# [4,5,7,8]   [16,17,19,20], [28,29,31,32]뽑아내기!
arr[0:,1:3,0:2]

array([[[ 4,  5],
        [ 7,  8]],

       [[16, 17],
        [19, 20]],

       [[28, 29],
        [31, 32]]])

In [ ]:
# [8,9,11,12], [32,33,35,36]
arr[0::2,2:,1:]

array([[[ 8,  9],
        [11, 12]],

       [[32, 33],
        [35, 36]]])

In [ ]:
# 고난이도! 4차원 배열 해보자! 텐서가 2개(텐서, 텐서)
arr = np.arange(36).reshape(2,3,3,2)
arr

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]]])

In [ ]:
arr[1,1,1:]

array([[26, 27],
       [28, 29]])

In [ ]:
arr[0, :,:,0]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
arr[0, ... , 0]  #... 쩜쩜쩜 써도됨 spread 연산자
# 특정 범위내에 있는 모든 데이터 한꺼번에 가져오기

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
arr[1,0,0,1]

19

# 보통 이미지 데이터를 딥러닝에서 사용하고자 할때
(N, H, W, C)

  - N : 이미지개수
  - H : 세로픽셀의 개수
  - W : 가로픽셀의 개수
  - C : 채널수(컬러 RGB:3, 흑백 GRATSCALE:1)

  노트그림 참고

# 배열의 차원(ndim)과 형상(shape)

In [ ]:
arr = np.arange(12).reshape(3,4)
arr.shape # 배열의 형상을 ⭐⭐튜플로 등장!!

(3, 4)

In [ ]:
arr.ndim # 행렬이니깐 2차원 배열

2

# 차원수 확장하기!
  - 보통 딥러닝에서 이미지 분석을 하기 위해 CNN 알고리즘을 화용한다.
  - CNN에 필요한 데이터의 형상이 따로 존재하는데, 이 알고리즘을 활용하기 위한 형상(shape)이 존재한다.
  -(N,H,W,C)의 형식을 유지해야 한다.

예시) 흑백 이미지를 수집했는데, 이 이미지의 형상정보(shape)을 확인해보니 (28,28)이라면?

CNN알고리즘에 이미지를 집어넣기 위해선
(1,28,28,1)의 형태로 만들어 줘야 한다.

## ⭐⭐⭐ np.newaxis

In [ ]:
# 흑백 이미지 한장을 가지고 있다!
image = np.random.rand(28,28)
image.shape # 2차원 행렬데이터면 안돼!!
            # 4차원으로 확장시켜주기위해 차원수 확장이필요 (1,28,28,1)로 만들어줘야


(28, 28)

In [ ]:
image_expanded_dim = image[np.newaxis, :, :,np.newaxis] # [newaxis, ... , newaxis]해줘도됨
image_expanded_dim.shape

(1, 28, 28, 1)

# 차원 쥐어짜기 np.squeeze
  - 개수가 1인 차원의 내용을 없애줌 5X1에서 1같은부분

  (1,28,28,1)에서 1같은부분

In [ ]:
temp_squeeze = np.squeeze(image_expanded_dim)
temp_squeeze.shape

# 의미가 있는 정보부분만 남겨줌

(28, 28)


# 배열의 형상바꾸기 ⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐
  - np.newaxis를 활용하면 축하나추가(차원수를 늘린다)
  - np.squeeze를 활용하면 개수가 1인 차원의 데이터를 삭제(차원수를 줄인다.)

평탄화: 2차원 이상의 배열을 1차원 배열로 평평하게 펴주는것⭐⭐⭐
  - ravel :  원본 배열을 평탄화 시킨 참조배열을 만들어 낸다.(이를 View 또는 Reference라고 한다.)
  - flatten : 원본 배열을 평탄화 시킨 복사된배열을 만들어 낸다.

ravel은 원본 배열에 수정이 가해질 가능성이 있고, flatten은 원본 배열에 영향을 미치지 않는다.

In [ ]:
x = np.random.randint(15, size=(3,5))  # 0~15까지수 랜덤
x.shape

(3, 5)

In [ ]:
x

array([[11,  4,  2,  6,  5],
       [ 3,  1, 11,  8,  0],
       [12, 12, 10, 14, 13]])

In [ ]:
temp = np.ravel(x)  # 1차원데이터 열벡터로 펴줘!!
temp.shape 

(15,)

In [ ]:
temp

array([11,  4,  2,  6,  5,  3,  1, 11,  8,  0, 12, 12, 10, 14, 13])

In [ ]:
temp[0] = 100
temp

array([100,   4,   2,   6,   5,   3,   1,  11,   8,   0,  12,  12,  10,
        14,  13])

In [ ]:
x 
# lst1 = lst2 ⭐참조🌜배열이라 temp바꾸면 원본x도 같이바뀜!

array([[100,   4,   2,   6,   5],
       [  3,   1,  11,   8,   0],
       [ 12,  12,  10,  14,  13]])

In [ ]:
x[1, 3] = 9999
temp

# x 바꿔도 temp도 같이바뀜

array([ 100,    4,    2,    6,    5,    3,    1,   11, 9999,    0,   12,
         12,   10,   14,   13])

In [ ]:
print(hex(id(x)))  # 원본
print(hex(id(temp)))  # 거울

print(hex(id(temp.base))) # 원본

# 근데 x랑 temp메모리 주소 다름.
# temp.base가 같음
# view또는 reference라고함

0x7f4b3f5fb4b0
0x7f4b3f5fbe10
0x7f4b3f5fb4b0


## flatten
데이터를 평탄화

In [ ]:
x = np.random.randint(15, size=(3,5))
x.shape

(3, 5)

In [ ]:
temp_flatten = x.flatten()
temp_flatten.shape

(15,)

In [ ]:
temp_flatten

array([14, 14,  8,  6,  7,  8,  5, 11,  4,  5, 10,  1,  3,  2, 12])

In [ ]:
temp_flatten[0] = 100
temp_flatten

array([100,  14,   8,   6,   7,   8,   5,  11,   4,   5,  10,   1,   3,
         2,  12])

In [ ]:
x # flatten은 복사라 원본에 영향없지롱

array([[14, 14,  8,  6,  7],
       [ 8,  5, 11,  4,  5],
       [10,  1,  3,  2, 12]])

# reshape
배열의 형상을 재구상하는 것


In [ ]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
x.size  # size 원소의 개수 확인가능

20

In [ ]:
# 형상을 재구상할 때 원소의 개수는 그대로여야대 2x5x2 = 20 🌜⭐
x.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## -1을 사용하면 남은 숫자를 자동으로 계산해줌

In [ ]:
x.reshape(2,-1,2)   # -1에 알아서 5들어감 

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [ ]:
x.reshape(4,-1) # 대신 2,3,-1 = 20 안됨 원소의 개수 맞아야함 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
x.reshape(2,-1,-1) # 이것도 안댐 1개밖에 못씀

ValueError: ignored

# reshape을 활용하면 평탄화도 할 수 있다.
x.reshape(-1)

In [ ]:
x.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
x.reshape(1,-1,1).shape

(1, 20, 1)

# 브로드캐스팅
  - 차원 수가 다른 배열끼리 연산!
  - 차원이 달라서 0차원 스칼라의 개수가 똑같으면 연산가능
  - ⭐저차원 배열을 >> 고차원 배열⭐|로 확장
  작은걸 올려줘야 큰거만지면안됨
  - 수학적으로 따지게 되면, 고차원 배열의 shape과 똑같은 1벡터(ones)를 만들어서 저차원 배열과 곱한 배열을 만들어서 계산

In [ ]:
# shape이 다를 때의 연산
a = np.arange(12).reshape(4, 3) # (4, 3)
b = np.arange(100, 103)         # (3, ) 원소가 3개인 1차원배열 배열은 가로로보기 ㅁㅁㅁ⭐⭐⭐
c = np.arange(1000, 1004)       # (4, )
d = b.reshape(1, 3)             # (1, 3) 행벡터
e = np.arange(0, 4).reshape(4, 1) # ( 4, 1) 열벡터

In [ ]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [ ]:
# a + c는 안됨 가로길이가 안맞앙
a + d  # (3,) 도되고 (1,3)도 됨!

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [ ]:
a + e

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])